### ISSUE TITLE
Error when utilizing Sails session config: routesDisabled

### ISSUE THREAD

**Issue by makmakulet** [dudemelo/sails-hook-flash#7]
Got the error below when hitting a route configured with routesDisabled

**Sails Version: 0.12.0**

> TypeError: Cannot read property 'flash' of undefined
>    at module.exports (/path/to/project/node_modules/sails-hook-flash/lib/flash.js:24:25)

Applied a dirty _.get() implementation on line 24 just to proceed.

`if (typeof _.get(req,"session[_session_key]", "") === 'undefined') {`

**Comment by jfmelo** [comment]
Hey @makmakulet , thanks for report, it was fixed on [v0.2.2](/dudemelo/sails-hook-flash/releases/tag/v0.2.2).
